### ISSUE TITLE
Debugger requirement: language-specific slot hiding

### ISSUE THREAD

**Issue by mlvdv** [graalvm/truffle#157]
The debugger needs to decide which stack frame slots to display during normal debugging. What's needed is a language-specific recommendation on whether the name and value of any given slot would be sensible (useful) to a guest language programmer.

The debugger might display such slots anyway, for example in a special mode for language implementors.

@mickjordan reports that this would be useful for current work

**Comment by entlicher** [comment]
What if we change `Object FrameSlot.getInfo()`, which says nothing from the API point of view and serves to a particular language implementor only, who know what info they put into `DrameDescriptor.addFrameSlot()`, to a better typed `FrameSlotInfo FrameSlot.getInfo()`?
`FrameSlotInfo` can have then `<T> T FrameSlot.getCapability(Class<T> capability)` (inspired by `TruffleRuntime`).
This would add a flexibility to functionally evolve the APIs.
We could also have a more generic `CapabilityProvider` interface instead of `FrameSlotInfo`, that could be reused on more places.
Thoughts?

**Comment by jtulach** [comment]
Using `getCapability` is useful if you want to *tunnel* through some API - e.g. create a [teleinterface](http://wiki.apidesign.org/wiki/Teleinterface). I may be wrong, but I don't think we need that for slots.

**Comment by chumer** [comment]
Yes I liked the FrameFormat SPI idea that is implemented by the language can be passed into the FrameDescriptor. 

FrameFormat#isVisible(FrameSlot)
FrameFormat#isReadable(FrameSlot)
FrameFormat#isWritable(FrameSlot)
FrameFormat#getName(FrameSlot)
...

The FrameFormat can be null for a descriptor which means nothing is visible, nothing is readable/writable and an obfuscated name (like arg0, arg1).

I dislike FrameSlotInfo because it requires an additional allocation for each slot whereas FrameFormat could be shared accross a language.

**Comment by lukasstadler** [comment]
how about the following heuristic: only frame slots with String identifiers are visible in the debugger.

**Comment by chumer** [comment]
Some languages might not want to use String identifiers. I also think we should be conservative if a variable is not explicitly exported.

**Comment by entlicher** [comment]
Is there some example of such non-String identifiers and an idea of how should debugger treat them?
Debugger needs to convert everything to a String in the end to display it meaningfully.

**Comment by mlvdv** [comment]
>how about the following heuristic: only frame slots with String identifiers are visible in the debugger.

This would conflate two separate issues:  
- naming (and how names should be displayed to users)
- whether a particular slot (or frame, or anything else) should be displayed during ordinary operation.

The debugger should be able to display *all* slots when in special modes (not for guest language programmers), and names could be very helpful in those modes.

**Comment by chumer** [comment]
Tracked elsewhere: GR-89
