### ISSUE TITLE
SourceSection handling in Node

### ISSUE THREAD

**Issue by smarr** [graalvm/truffle#25]
What is the future of [`Node.assignSourceSection()`](https://github.com/graalvm/truffle/blob/master/truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/Node.java#L84)?

Currently, the reassigning of a source section is protected by an `IllegalStateException`.
However, the API also provides a `public clearSourceSection()`, which enables reassignment.

The main reason for this issue is that the API is marked for revision, so, I hope we can settle on an API considering for instance the needs for the new instrumentation API.

@chumer suggested as solution a `protected setSourceSection(.)`, which could be used depending on a language's needs.

Other interested parties are most likely @woess and @jtulach.

A little bit of background: the new instrumentation API currently manages tags as part of `SourceSection`s. For me this creates the need to reassign the source sections on a node.
The situation in SOMns is, that I got a recursive descent parser, and thus, for instance when parsing expression trees recursively, I might only know after creating a full node with source section and state etc that I needs a tag for some tool. So, I got the need to update the tag and reassign the source section.
Using `clearSourceSection()` the use case is supported.

**Comment by jtulach** [comment]
There is an attempt to lower the memory consumption and I am surprised we still carry the SourceSection field for all nodes - in spite just a few of them really use it. I would keep just the getSourceSection method and remove all the other methods. I am sure every language can create its own 
```
@CompilationFinal private SourceSection sourceSection;
```
and work with it properly.

**Comment by smarr** [comment]
To address the point of the usage of the source section: This might evolve based on the instrumentation API and how tagging is going to work.

As I see it, trying to implement a tool with the API, actually a great many nodes need the source section because that's where the tags go. So, not sure removing `sourceSection` is really an improvement at this point.

**Comment by chumer** [comment]
@jtulach the instrumentation API needs Node#getSourceSection(). I guess you would make getSourceSection() return null by default if we remove the field?

**Comment by chumer** [comment]
I'd be in favor of removing the Node#sourceSection field.

**Comment by chumer** [comment]
@woess What do you think about this?

**Comment by woess** [comment]
looping in @mlvdv

**Comment by mickjordan** [comment]
The FastR design explicitly denotes nodes that contain source sections via the RSyntaxNode interface. We have a subclass of Node that overrides the source section methods and throws an error if anyone tries to set/get a source section from a non-syntax node. Certainly there is no a priori need for the source section to actually be stored in the node. We do need to clear/assign source sections, rarely, for some of the reflection methods in R. For example, one can modify an existing AST using the "substitute" builtin, which may replace names etc. in the tree with different values.

**Comment by mlvdv** [comment]
Do we have any stats on the percentage of nodes in Truffle ASTs that are "syntax nodes", i.e. ones that are subject to the currently supported kind of instrumentation (based on SourceSection matching)?

**Comment by mlvdv** [comment]
I have been assuming for some time that Mick's approach (making the notion of a `SyntaxNode` first class in the platform) is the best approach, so there would only be `getSourceSection()` for those nodes.  Hoisting this approach into `Node`, to be provided by all language implementations, was discussed some time back, but declined for lack of enthusiasm.

**Comment by woess** [comment]
(sorry, thought I had already commented, but apparently I forgot to submit)
I too would like to see some data on the relative number of nodes with source sections in language implementations and associated impact on memory footprint. That said, I think it's reasonable to let language implementations take on ownership of source sections of nodes, for the very reason that a lot of nodes don't actually need one. Conversely, it might be a bit more error-prone.

Then there's the question of when to assign source sections. We at some point considered assigning all source sections in the constructor (only), to make it clear that they be non-optional. With the nice property that they could be made final. But it turned out to be awkward at times and again, not all nodes actually require source attribution.
But it brings up an important question: is it ok to change source attribution after parse time? The answer is probably no, and it's something instrumentation relies upon.

**Comment by mickjordan** [comment]
On 2/1/16 7:02 PM, Andreas Woess wrote:
>
> (sorry, thought I had already commented, but apparently I forgot to 
> submit)
> I too would like to see some data on the relative number of nodes with 
> source sections in language implementations and associated impact on 
> memory footprint. That said, I think it's reasonable to let language 
> implementations take on ownership of source sections of nodes, for the 
> very reason that a lot of nodes don't actually need one. Conversely, 
> it might be a bit more error-prone.
>
I think there should be generic support for source sections management 
in truffle, but I don't think there should be a field in Node.
>
> Then there's the question of when to assign source sections. We at 
> some point considered assigning all source sections in the constructor 
> (only), to make it clear that they be non-optional. With the nice 
> property that they could be made final. But it turned out to be 
> awkward at times and again, not all nodes actually require source 
> attribution.
> But it brings up an important question: is it ok to change source 
> attribution after parse time? The answer is probably no, and it's 
> something instrumentation relies upon.
>
>
Define "parse time". For example, the (Fast)R substitute builtin clones 
an existing AST and then transforms it in ways specified by the function 
caller. This is done by a tree walk and on return from a node, the 
source section is recomputed and re-assigned. It would be very painful 
to recast this process in such a way that we had to call a constructor 
if that were the only way to set the source section. I'm fairly 
confident the instrumentation system can specify appropriate invariants 
regarding the update of source sections and that the substitute process 
I described above would have no difficulty complying, since 
instrumentation doesn't happen until the transformed tree is actually 
evaluated.

Mick

**Comment by jtulach** [comment]
A typical (node-like) application may have 2:1 ratio in favor of of "non-source section nodes". Query from VisualVM OQL taken after booting up the command prompt follows:
```js
select count(heap.objects('com.oracle.truffle.api.nodes.Node', true, "it.sourceSection != null"))
68075
select count(heap.objects('com.oracle.truffle.api.nodes.Node', true, "it.sourceSection == null"))
127688
```

**Comment by smarr** [comment]
For a run of DeltaBlue, instrumented with my DynamicMetrics tool, I get the following results:
`sourceSection != null`: 18082
`sourceSection == null`: 10754

So, here it is reversed, and, I am not yet getting all the data I need. I'll need to add source sections to more nodes in order to be able to tag them.

**Comment by jtulach** [comment]
Here is sketch of how the removal would look like: https://github.com/jtulach/truffle/commit/c77efc18667568f17858a79a079b4ebb5619bd27 - a question remains: should we also remove SourceSection from RootNode's constructor? What are your data about RootNodes in your languages?

**Comment by woess** [comment]
I'd define "parse time" vaguely as the time before first execution. As I understand, your substitute use case would be supported by this definition. If source sections change during execution, things get messy, so ideally you'd want to prohibit that.

@jtulach pretty much all our RootNodes have SourceSections (except tests).

**Comment by mickjordan** [comment]
On 2/1/16 2:53 PM, Michael Van De Vanter wrote:
>
> Do we have any stats on the percentage of nodes in Truffle ASTs that 
> are "syntax nodes", i.e. ones that are subject to the currently 
> supported kind of instrumentation (based on SourceSection matching)?
>
>

I added the capability to gather this information for R functions. For 
"real" functions, i.e. ones that are more than one liners, FastR starts 
about 55/45% syntax/non-syntax. After execution it changes to around 
80/20. E.g., the main function of shootout.pidigits:

After parse:

$PiDigits
      Total     Syntax Non-Syntax
        264        134        130

After execution:

$PiDigits
      Total     Syntax Non-Syntax
        971        790        181

**Comment by lukasstadler** [comment]
some node types (e.g., builtins) are still syntax nodes although they shouldn’t be - so the numbers will be skewed somewhat in favor of non-syntax nodes soon.

**Comment by mickjordan** [comment]
On 2/3/16 8:34 AM, Lukas Stadler wrote:
>
> some node types (e.g., builtins) are still syntax nodes although they 
> shouldn’t be - so the numbers will be skewed somewhat in favor of 
> non-syntax nodes soon.
>
>
Yes, we need to fix that, and make sure getRSyntaxNode() can get to the 
original RCallNode that has the syntax.

Mick

**Comment by mickjordan** [comment]
On 2/3/16 8:28 AM, Mick Jordan wrote:
> On 2/1/16 2:53 PM, Michael Van De Vanter wrote:
>>
>> Do we have any stats on the percentage of nodes in Truffle ASTs that 
>> are "syntax nodes", i.e. ones that are subject to the currently 
>> supported kind of instrumentation (based on SourceSection matching)?
>>
I had the labels inverted in the previous message. After Lukas noted 
that the nodes we used for builtin functions were erroneously tagged as 
syntax nodes, I fixed that which, of course, reduced the number in the 
"after-execution" state. So shootout.pidigits now has:

After parse:

$PiDigits
      Total     Syntax Non-Syntax
        264        130        134

After execution:

$PiDigits
      Total     Syntax Non-Syntax
        971        169        802

You might wonder why the number of syntax node increases. This is 
because some node classes tagged statically as syntax nodes are also 
used as children of nodes transformed during execution, so they don't 
correspond to the source as parsed. For example for loops are rewritten 
in such a way that some syntax nodes are duplicated. Although we have 
the API for it, we don't currently distinguish these different use cases 
in most transformations. Similarly we do some transformation up-front in 
the code that converts the ANTLR parse tree to the Truffle AST, which is 
why there are non-syntax nodes after the parse.

I fully expect these numbers to hold up across the majority of R code. 
Evidently some footprint could be saved by moving the source section 
info out of the Node class.

Mick

**Comment by jtulach** [comment]
Great to hear confirmation that "some footprint could be saved by moving the source section info out of the Node class". I'll work towards that.

**Comment by woess** [comment]
@mickjordan thanks for the numbers (which confirm my expectations).

**Comment by jtulach** [comment]
I am about to integrate #35 - deprecate Node(SourceSection) constructor, Node#assignSourceSection and Node#clearSourceSection. You can stop me by tomorrow.

**Comment by jtulach** [comment]
#35 is in. Closing.
